### ISSUE TITLE
Crash on multiple window

### ISSUE THREAD

**Issue by licaon-kter** [SpartanJ/ImgurViewer#46]
2.3.3 F-Droid

Open an url

Go to task overview, trigger multiple windows (or split screen or whatever that is called)

Crash
```
FATAL EXCEPTION: main
Process: com.ensoft.imgurviewer, PID: 10365
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window androidx.fragment.app.FragmentActivity.getWindow()' on a null object reference
	at com.ensoft.imgurviewer.view.fragment.ImageViewerFragment.setSystemUiVisibility(ImageViewerFragment.java:721)
	at com.ensoft.imgurviewer.view.fragment.ImageViewerFragment.access$500(ImageViewerFragment.java:81)
	at com.ensoft.imgurviewer.view.fragment.ImageViewerFragment$7.run(ImageViewerFragment.java:747)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by SpartanJ** [comment]
Thanks for reporting it. I'll take a look.
